fn main() void {
    print("Helloworld", "maman", "Harold", "Reese",);
    fn_call("I like to play with people");
    var sub: i32 = "Bonjour";
    if "bonjour" {
        print("in if statement");
        foo("in foo statement");
        if "maman" {
            bar("foo", "bar", "baz",);
            var inner_var: Foo = "bonsoir";
        } elseif "else_expr" {
            fn_else("in_fn_else",);
        }
    } elseif "else_if_expr" {
        bazz("in bazz");
    }
}
